apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lovely-server
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - lovely.example.com
      secretName: lovely-tls
  rules:
    - host: lovely.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lovely-server
                port:
                  number: 8080
