ALTER TABLE pages DROP COLUMN IF EXISTS unlisted;
ALTER TABLE pages DROP COLUMN IF EXISTS password_hash;
ALTER TABLE pages DROP COLUMN IF EXISTS head_html;
ALTER TABLE apps DROP COLUMN IF EXISTS theme_json;
